steps:
# TODO: hardcoded:
#       location=us-central1-b
#       project=diets-325702

# clone a specific branch for batch runs
- id: 'clone'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', '-b','batch-run', 'https://github.com/semiformal-net/diet_api.git','/workspace/diet_api-environment']

- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/diets-325702/diet_api:batch', '/workspace/diet_api-environment' ]

- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/diets-325702/diet_api:batch']

#- id: 'deploy image'
#  name: 'gcr.io/cloud-builders/gcloud'
#  args: ['compute', 'instances', 'create-with-container', 'dietapibatch', '--zone=us-east1-b', '--container-image=gcr.io/diets-325702/diet_api:batch','--machine-type=e2-highcpu-4', '--network-tier=STANDARD','--network=default','--no-address','--image-project=cos-cloud','--image-family=cos-stable']
